export WORK_SSH_HOST='{{ op://dotfiles/work/ssh/host }}'
export WORK_SSH_USER='{{ op://dotfiles/work/ssh/user }}'
export WORK_ECR_REGISTRY='{{ op://dotfiles/work/aws/ecr-registry }}'
export WORK_SPHINX_IMAGE='{{ op://dotfiles/work/aws/sphinx-image }}'
export WORK_NPM_REGISTRY='{{ op://dotfiles/work/npm/registry }}'
export DEVSHELL_PG_USER='{{ op://dotfiles/work/nix/pg-user }}'
export DEVSHELL_PG_DATABASE='{{ op://dotfiles/work/nix/pg-database }}'
export DEVSHELL_PG_PASSWORD='{{ op://dotfiles/work/nix/pg-password }}'
